services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword      # root 的密码，你随便改成强一点的也行
      MYSQL_DATABASE: blog                   # 启动时自动创建 blog 库
      MYSQL_USER: nest_user                  # 普通用户
      MYSQL_PASSWORD: VH520Avril             # 普通用户密码
    ports:
      - "3306:3306"                          # 如果你本机已有 MySQL 占着 3306，可以改成 "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: ["--default-authentication-plugin=mysql_native_password"]

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-project-api
    restart: always
    env_file:
      - .env                                  # 让 Nest 读这里的环境变量
    depends_on:
      - db
    ports:
      - "3000:3000"
    command: ["node", "dist/src/main.js"]

volumes:
  db_data:
